### ISSUE TITLE
ErrorException: Undefined Property - $imageTemplate

### ISSUE THREAD

**Issue by Luehrsen** [Xon/XenForo2-LazyImageLoader#8]
https://github.com/Xon/XenForo2-LazyImageLoader/blob/2b9011a846dd97f7b83e5790e1d3c5f9cc8b15f2/upload/src/addons/SV/LazyImageLoader/XF/BbCode/Renderer/Html.php#L63

This piece of code throws a notice. In itself not a huge deal, but I see it seems already fixed in later commits. If you could release an update with the current commits, that would be golden. 

Thanks for the awesome work!

**Stack Trace**
```
#0 src/addons/SV/LazyImageLoader/XF/BbCode/Renderer/Html.php(63): XF::handlePhpError(8, '[E_NOTICE] Unde...', '/kunden/603864_...', 63, Array)
#1 [internal function]: SV\LazyImageLoader\XF\BbCode\Renderer\Html->renderTagImage(Array, NULL, Array, Array, Object(SV\LazyImageLoader\XF\BbCode\Renderer\Html))
#2 src/XF/BbCode/Renderer/Html.php(307): call_user_func(Array, Array, NULL, Array, Array, Object(SV\LazyImageLoader\XF\BbCode\Renderer\Html))
#3 src/XF/BbCode/Traverser.php(61): XF\BbCode\Renderer\Html->renderTag(Array, Array)
#4 src/XF/BbCode/Renderer/Html.php(445): XF\BbCode\Traverser->renderSubTree(Array, Array)
#5 [internal function]: XF\BbCode\Renderer\Html->renderTagAlign(Array, NULL, Array, Array, Object(SV\LazyImageLoader\XF\BbCode\Renderer\Html))
#6 src/XF/BbCode/Renderer/Html.php(307): call_user_func(Array, Array, NULL, Array, Array, Object(SV\LazyImageLoader\XF\BbCode\Renderer\Html))
#7 src/XF/BbCode/Traverser.php(61): XF\BbCode\Renderer\Html->renderTag(Array, Array)
#8 src/XF/BbCode/Traverser.php(37): XF\BbCode\Traverser->renderSubTree(Array, Array)
#9 src/XF/BbCode/Traverser.php(20): XF\BbCode\Traverser->renderAst(Array, Object(XF\BbCode\RuleSet), Array)
#10 src/XF/Pub/View/FeedHelper.php(118): XF\BbCode\Traverser->render('[CENTER][SIZE=6...', Object(XF\BbCode\Parser), Object(XF\BbCode\RuleSet), Array)
#11 src/XF/Pub/View/Forum/Rss.php(42): XF\Pub\View\FeedHelper::setupEntryForThread(Object(Laminas\Feed\Writer\Entry), Object(XFMG\XF\Entity\Thread), 'last_post_date')
#12 src/XF/Mvc/Renderer/AbstractRenderer.php(91): XF\Pub\View\Forum\Rss->renderRss()
#13 src/XF/Mvc/Renderer/Xml.php(74): XF\Mvc\Renderer\AbstractRenderer->renderViewObject('XF:Forum\\Rss', '', Array)
#14 src/XF/Mvc/Dispatcher.php(458): XF\Mvc\Renderer\Xml->renderView('XF:Forum\\Rss', '', Array)
#15 src/XF/Mvc/Dispatcher.php(440): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Rss), Object(XF\Mvc\Reply\View))
#16 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Rss), Object(XF\Mvc\Reply\View))
#17 src/XF/Mvc/Dispatcher.php(58): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'rss')
#18 src/XF/App.php(2300): XF\Mvc\Dispatcher->run()
#19 src/XF.php(465): XF\App->run()
#20 index.php(20): XF::runApp('XF\\Pub\\App')
#21 {main}
```

**Comment by Xon** [comment]
The release version isn't XF2.2 compatible, latest master should be but hasn't been fully tested yet.
